"use client";

import {
  HedgehogActorOptions,
  HedgehogActorColorOptions,
  HedgehogActorAccessoryOptions,
  HedgehogActorSkinOptions,
  HedgehogActorAccessories,
  HedgehogActorAccessoryOption,
  CSSStaticHedgehog,
} from "@posthog/hedgehog-mode";
import { uniqueId } from "lodash";

// NOTE: 100% generated by ChatGPT for fun!
function mulberry32(seed: number) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function deterministicShuffle<T>(array: T[], seed: number): T[] {
  const rng = mulberry32(seed);
  const arr = array.slice(); // copy to avoid mutating original
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Generate all combinations of accessories, colors, and skins
let allCombinations = Object.values(HedgehogActorAccessoryOptions).flatMap(
  (accessory) =>
    Object.values(HedgehogActorColorOptions).flatMap((color) =>
      Object.values(HedgehogActorSkinOptions).map(
        (skin): HedgehogActorOptions => ({
          id: `hedgehog-${uniqueId()}`,
          accessories: [accessory],
          color,
          skin,
        })
      )
    )
);

const accessoriesByGroup = Object.entries(HedgehogActorAccessories).reduce(
  (acc, [key, value]) => {
    acc[value.group] = acc[value.group] || [];
    acc[value.group].push(key as HedgehogActorAccessoryOption);
    return acc;
  },
  {} as Record<string, HedgehogActorAccessoryOption[]>
);

function generateCombos(): HedgehogActorAccessoryOption[][] {
  const out: HedgehogActorAccessoryOption[][] = [];

  const H = accessoriesByGroup.headwear;
  const E = accessoriesByGroup.eyewear;
  const O = accessoriesByGroup.other;

  // singles
  for (const a of [...H, ...E, ...O]) out.push([a]);

  // pairs: H+E, H+O, E+O
  for (const h of H) for (const e of E) out.push([h, e]);
  for (const h of H) for (const o of O) out.push([h, o]);
  for (const e of E) for (const o of O) out.push([e, o]);

  // triples: H+E+O
  for (const h of H) for (const e of E) for (const o of O) out.push([h, e, o]);

  return out;
}

// If you truly need a Set (e.g., for uniqueness or fast lookups), serialize:
function toKey(combo: HedgehogActorAccessoryOption[]): string {
  // sort to make order-insensitive keys if you like
  return [...combo].sort().join("|");
}

const combos = generateCombos();
const comboSet = new Set(combos.map(toKey));

// Create all possible combination of accessories by group
const accessories: HedgehogActorOptions[] = Array.from(comboSet).map(
  (accessories) => ({
    accessories: accessories
      .split("|")
      .map((a) => a as HedgehogActorAccessoryOption),
    id: `hedgehog-${uniqueId()}`,
    skin: "default",
  })
);

// Deterministically shuffle the array
allCombinations = deterministicShuffle(allCombinations, 42);

export default function StaticRendering() {
  return (
    <div className="p-8 flex flex-col gap-2">
      <div>
        <h2 className="text-2xl font-bold">Accessories (CSS)</h2>
        <div className="flex flex-wrap gap-2">
          {accessories.map((hedgehog, i) => (
            <span key={i} title={JSON.stringify(hedgehog)} className="relative">
              <CSSStaticHedgehog
                options={hedgehog}
                size={80}
                assetsUrl="/assets"
              />
            </span>
          ))}
        </div>
      </div>
      <div>
        <h2 className="text-2xl font-bold">Colors (CSS)</h2>
        <div className="flex flex-wrap gap-2">
          {HedgehogActorColorOptions.map((color) => (
            <span key={color} title={color} className="relative">
              <CSSStaticHedgehog
                options={{ id: `hedgehog-${uniqueId()}`, color }}
                size={80}
                assetsUrl="/assets"
              />
            </span>
          ))}
        </div>
      </div>
      <div>
        <h2 className="text-2xl font-bold">All combinations (CSS)</h2>
        <div className="flex flex-wrap gap-2">
          {allCombinations.map((hedgehog, i) => (
            <span key={i} title={JSON.stringify(hedgehog)} className="relative">
              <CSSStaticHedgehog
                options={hedgehog}
                size={80}
                assetsUrl="/assets"
              />
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
