"use client";

import {
  HedgehogActorOptions,
  HedgehogActorColorOptions,
  StaticHedgehogRenderer,
  HedgehogActorAccessoryOptions,
  HedgehogActorSkinOptions,
  HedgehogActorAccessories,
  HedgehogActorAccessoryOption,
} from "@posthog/hedgehog-mode";
import { uniqueId } from "lodash";
import { useEffect, useRef, useState } from "react";

// NOTE: 100% generated by ChatGPT for fun!
function mulberry32(seed: number) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function deterministicShuffle<T>(array: T[], seed: number): T[] {
  const rng = mulberry32(seed);
  const arr = array.slice(); // copy to avoid mutating original
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Generate all combinations of accessories, colors, and skins
let allCombinations = Object.values(HedgehogActorAccessoryOptions).flatMap(
  (accessory) =>
    Object.values(HedgehogActorColorOptions).flatMap((color) =>
      Object.values(HedgehogActorSkinOptions).map(
        (skin): HedgehogActorOptions => ({
          id: `hedgehog-${uniqueId()}`,
          accessories: [accessory],
          color,
          skin,
        })
      )
    )
);

const accessoriesByGroup = Object.entries(HedgehogActorAccessories).reduce(
  (acc, [key, value]) => {
    acc[value.group] = acc[value.group] || [];
    acc[value.group].push(key as HedgehogActorAccessoryOption);
    return acc;
  },
  {} as Record<string, HedgehogActorAccessoryOption[]>
);

function generateCombos(): HedgehogActorAccessoryOption[][] {
  const out: HedgehogActorAccessoryOption[][] = [];

  const H = accessoriesByGroup.headwear;
  const E = accessoriesByGroup.eyewear;
  const O = accessoriesByGroup.other;

  // singles
  for (const a of [...H, ...E, ...O]) out.push([a]);

  // pairs: H+E, H+O, E+O
  for (const h of H) for (const e of E) out.push([h, e]);
  for (const h of H) for (const o of O) out.push([h, o]);
  for (const e of E) for (const o of O) out.push([e, o]);

  // triples: H+E+O
  for (const h of H) for (const e of E) for (const o of O) out.push([h, e, o]);

  return out;
}

// If you truly need a Set (e.g., for uniqueness or fast lookups), serialize:
function toKey(combo: HedgehogActorAccessoryOption[]): string {
  // sort to make order-insensitive keys if you like
  return [...combo].sort().join("|");
}

const combos = generateCombos();
const comboSet = new Set(combos.map(toKey));

// Create all possible combination of accessories by group
const accessories: HedgehogActorOptions[] = Array.from(comboSet).map(
  (accessories) => ({
    accessories: accessories
      .split("|")
      .map((a) => a as HedgehogActorAccessoryOption),
    id: `hedgehog-${uniqueId()}`,
    skin: "default",
  })
);

// Deterministically shuffle the array
allCombinations = deterministicShuffle(allCombinations, 42);

function StaticHedgehog({
  hedgehog,
  renderer,
}: {
  hedgehog: HedgehogActorOptions;
  renderer: StaticHedgehogRenderer;
}) {
  const [image, setImage] = useState<string | null>(null);

  useEffect(() => {
    renderer.render(hedgehog, 160).then((image) => {
      setImage(image);
    });
  }, [hedgehog]);

  return (
    <>
      {!image ? (
        <div className="w-20 h-20 bg-gray-200" />
      ) : (
        <img width={80} height={80} src={image} />
      )}
    </>
  );
}

export default function StaticRendering() {
  const rendererRef = useRef<StaticHedgehogRenderer>();

  if (!rendererRef.current) {
    rendererRef.current = new StaticHedgehogRenderer({
      assetsUrl: "/assets",
    });
  }

  return (
    <div className="p-8 flex flex-col gap-2">
      <div>
        <h2 className="text-2xl font-bold">Accessories</h2>
        <div className="flex flex-wrap gap-2">
          {accessories.map((hedgehog, i) => (
            <StaticHedgehog
              hedgehog={hedgehog}
              renderer={rendererRef.current!}
              key={i}
            />
          ))}
        </div>
      </div>
      <div>
        <h2 className="text-2xl font-bold">All combinations</h2>
        <div className="flex flex-wrap gap-2">
          {allCombinations.map((hedgehog, i) => (
            <StaticHedgehog
              hedgehog={hedgehog}
              renderer={rendererRef.current!}
              key={i}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
