// Generated by the hedgehog prop generator — do not edit by hand.
// How far each skin's body sits below its resting height in each frame, so
// a held flag can follow it (e.g. crouching into a jump).
export const BODY_Y_OFFSETS: Record<string, Record<string, number[]>> = {
  default: {
    idle: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ],
    walk: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    jump: [0, 1, 0, 1, 0, -3, -4, -2, -1, 0],
    fall: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  ghost: {
    idle: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  hogzilla: {
    idle: [0],
    walk: [0, 0, 3, 6, 3, 0, 0, 0, 0, 0],
    jump: [3, 4, 3, 3, 3, 0, -1, 1, 3, 3],
    fall: [1, 1, 1, 1, 1, 1, 1, 1, 1],
  },
  robohog: {
    idle: [0],
    walk: [0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    jump: [0, 1, 0, 1, 0, -3, -4, -2, -1, 0],
    fall: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  spiderhog: {
    idle: [0],
    walk: [0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    jump: [0, 1, 0, 1, 0, -3, -4, -2, -1, 0],
    fall: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
};
