// Generated by the hedgehog prop generator — do not edit by hand.
// Positions relative to the centre of an 80x80 body frame.

/** Top-left of a flag's cloth: the top of the pole, on its fly side. */
export const FLAG_CLOTH_ORIGIN = { x: 10, y: -38 };

/** Centre of the hugged globe. */
export const FLAG_GLOBE_CENTER = { x: 7, y: 19 };
